### ISSUE TITLE
Pregunta

### ISSUE THREAD

**Issue by Isameneses12** [AlexisMunera98/wwc-python-reto-2#1]
Hola Alexis, aquí también tengo duda. Mira la flecha porfa 

import pandas 
def generar_dataframe_palabras(text):
    # Escribe el codigo para generar el diccionario con las ocurrencias de cada palabra

    lista_neruda= neruda.split()
    freq_palab = [lista_neruda.count(p) for p in lista_neruda]
    dicc= dict(list(zip(lista_neruda,freq_palab)))
   
    
    
    # Convertir el diccionario de ocurrencias en un Dataframe usando panda
    
    dataframe= pandas.DataFrame.from_dict(dicc, orient="index")
    return dataframe 
------------------------------------------------------------------>>> Aquí mi función devuelve un Dataframe, pero abajo en la comprobación, vuelve y lo genera, entonces sale un error! Si comento las lineas que tu tienes y que generan el dataframe, el ejercicio sale bien. Entonces no sé qué hacer.

neruda = """Puedo escribir los versos más tristes esta noche.
            Yo la quise, y a veces ella también me quiso.
            En las noches como ésta la tuve entre mis brazos.
            La besé tantas veces bajo el cielo infinito.
            
            Ella me quiso, a veces yo también la quería.
            Cómo no haber amado sus grandes ojos fijos.""".lower()  # lower hace que todas las letras sean minúsculas.

if __name__ == '__main__':
    d = generar_dataframe_palabras(neruda)
    print(d)
    df = pandas.DataFrame.from_dict(d, orient='index')
    print(df)
    assert isinstance(d, pandas.DataFrame), "Aun no generas un Dataframe, verifica tu algoritmo!"
    print("Excelente, has convertido un poema en un Dataframe para trabajar con el!")

```

    return texto_a_limpiar


if __name__ == '__main__':
    texto_entrada = "The NEW python prograMMER is a GREAT person. He is EXCEllent solving problems OF CODING anD " \
                    "writING scrIPts tO solve moDErn problems"
    texto_procesado = limpiar_stop_words(texto_entrada)
    texto_limpio = "the new python programmer a great person. he excellent solving problems of coding and writing " \
                   "scripts to solve modern problems"
    assert texto_limpio == texto_procesado, "Tu función aun no limpia de forma correcta"
    print("Tu limpiador de texto funciona!. FELICITACIONES!!!")

**Comment by AlexisMunera98** [comment]
Hola Isa, lo que pasa es que no deberías de modificar el main, solo completar el código de la función "generar_dataframe_palabras". Con respecto al error de las palabras stopwords si noté que hay un problema, en el menor tiempo posible subo la nueva versión para que se corrija.

**Comment by Isameneses12** [comment]
Sí, fue una raro porque la semana pasada bajé un código y tenía esa línea de código. Igual ya ese reto me funcionó y con el otro de las stopwords, lo que hice fue primero eliminar las stopwords y luego convertirlas a minúsculas. Así funciona con el assert.

Gracias!!!

**Comment by AlexisMunera98** [comment]
Acabo de actualizar el código fuente de la prueba para que ahora no haya problema con los stopwords. Voy a cerrar el PR si ves algún otro problema no dudes en abrir uno nuevamente
